### ISSUE TITLE
Support for inserting arrays in admin

### ISSUE THREAD

**Issue by tsilva** [hivesolutions/appier_extras#2]
## Description

Currently when I insert data for an item of list type it's converted and saved as an array with one string. In the admin interface it appears correctly:

<img width="935" alt="screenshot 2015-09-25 16 29 25" src="https://cloud.githubusercontent.com/assets/26742/10104698/ff697bb0-63a2-11e5-9942-13d0f671b383.png">

But when I retrieve the data itself, the items were turned into a string:

<img width="1066" alt="screenshot 2015-09-25 16 30 11" src="https://cloud.githubusercontent.com/assets/26742/10104718/20676f66-63a3-11e5-94c1-d0ce5d98de80.png">

**Comment by joamag** [comment]
@tsilva in the interface it's not correct either note the u" evolves the various elements. The problem is in the create interface for multiple values it does not allow proper string values

**Comment by joamag** [comment]
This is now considered fixed under the latest version of `appier` and `appier_extras`.
